import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";
import "@/styles/themes.css";
import { ColorPreload } from "@/components/layouts/color-preload";
import { Providers } from "@/components/providers";

const geist = Geist({
	variable: "--font-geist",
	display: "swap",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-mono",
	display: "swap",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geist.variable} ${geistMono.variable} antialiased`}>
				<Providers>{children}</Providers>
				<ColorPreload />
			</body>
		</html>
	);
}
